// Generated by scripts/generate-private-assets.mjs from the private Vite entry.
export const privateAssets = [
  "/private-assets/index-DPwZV7hU.js",
  "/private-assets/index-aybDajOK.css",
  "/private-assets/navigation-DlwKUEtn.js",
  "/private-assets/react-BuZFbSos.js",
  "/private-assets/ui-C_qyQo3F.js",
] as const;
