// Generated by scripts/generate-private-assets.mjs from the private Vite entry.
export const privateAssets = [
  "/private-assets/index-CUHDVaHS.css",
  "/private-assets/index-CbfZ7rhm.js",
  "/private-assets/navigation-BH7JvOjC.js",
  "/private-assets/react-BuZFbSos.js",
  "/private-assets/ui-C_qyQo3F.js",
] as const;
