// Generated by scripts/generate-public-assets.mjs.
export const publicManifest = {
  page: {
    integrity: "sha384-2cGKLCl/md2fJq0Fz/HhqPaE5VVAhw8pU6qI9GRJu71D7IPMXBGNoBkcHOm96CJc",
    bytes: 899,
  },
  assets: [
    {
      path: "/public-assets/public-share.qT9s6OaU.js",
      auth: "public",
      integrity: "sha384-FT1pwBr+r4PFsYgW68kZsDfOs4dX11RKDQHtUZY0yGqC+RpIvn9AlcT8BdNAFfGl",
      bytes: 300497,
    },
    {
      path: "/public-assets/public-share.BkQXpKXi.css",
      auth: "public",
      integrity: "sha384-LWneT4UhUEv8m1qIKuOWmNtl0wmPHqfCG2n+OApLhDgJZW91ZLcRJSL98B1AvQEp",
      bytes: 9985,
    },
  ],
} as const;
