// Generated by scripts/generate-public-assets.mjs.
export const publicManifest = {
  page: {
    integrity: "sha384-Ia9ZK4gmJ2A0IbP1eJrJ06l8VSt+h12rzr/Bq5+hkZx6b+DV5ELYdFJ0X5grBL1e",
    bytes: 899,
  },
  assets: [
    {
      path: "/public-assets/public-share.CUL2fDak.js",
      auth: "public",
      integrity: "sha384-iih1vsy5jLGdR8Rlbh44YM9gh8vgAHoemKEHNG2CjRwUn/OC1dOcqIZSCuPMC7PO",
      bytes: 295660,
    },
    {
      path: "/public-assets/public-share.NaAaDr-X.css",
      auth: "public",
      integrity: "sha384-CDRkw9cs+ez2uxX8RE6QB+U3zjFYO+Z8kgYTLKlKjX+ASpTK8EQFLW2upj638uzV",
      bytes: 9633,
    },
  ],
} as const;
