// Generated by scripts/generate-public-assets.mjs.
export const publicManifest = {
  page: {
    integrity: "sha384-uX6TlAMnoUWMOHbcrYuyKwc9iQfJTlMpH+Gr/1SnPWZtcVCHbARMa7NVuieJBFwB",
    bytes: 899,
  },
  assets: [
    {
      path: "/public-assets/public-share.DvJqV1k6.js",
      auth: "public",
      integrity: "sha384-DVKeVMiLvSz5h3ZB8loM+L/jIaU4t/A5jgyWHMZWNFVLyTnddU9FIQj7DU5Cpg6W",
      bytes: 277777,
    },
    {
      path: "/public-assets/public-share.B80TwWU8.css",
      auth: "public",
      integrity: "sha384-cAfmxTeYH1KnN9R52Tg5tNPX06SyFih53v8R2ogGGvP28nwVx3h58hv2nYDqmVxg",
      bytes: 7040,
    },
  ],
} as const;
