export const purgeOrder = [
  "trash_members",
  "node_props",
  "node_stars",
  "node_tags",
  "media_jobs",
  "node_media",
  "node_audio",
  "library_jobs",
  "archive_index",
  "user_reading_state",
  "user_playback_state",
  "content_sessions",
  "content_tickets",
  "zip_manifests",
  "share_sessions",
  "share_grants",
  "upload_parts",
  "uploads",
  "shares",
  "node_versions",
  "locks",
  "search_index",
  "library_items",
  "library_roots",
  "nodes",
] as const;

export type PurgeTable = (typeof purgeOrder)[number];
