// Generated from DESIGN §5.1 with IMPLEMENTATION_BRIEF §8 overrides.
import type { RouteContract } from "@next-cloud-flare/shared/contracts";

export const ROUTES = [
  {
    host: "app",
    method: "GET",
    template: "/",
    auth: ["access"],
    operation: "spa.read",
    operands: ["currentUser"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/assets/:asset",
    auth: ["access"],
    operation: "spa.read",
    operands: ["currentUser", "assetManifest"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/public-assets/:asset",
    auth: ["public"],
    operation: "public.asset.read",
    operands: ["publicAssetManifest"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/s",
    auth: ["public"],
    operation: "share.landing",
    operands: ["publicAssetManifest"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/s/:shareId",
    auth: ["public"],
    operation: "share.landing",
    operands: ["shareId", "publicAssetManifest"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/me",
    auth: ["access"],
    operation: "account.read",
    operands: ["currentUser"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/auth/logout",
    auth: ["access"],
    operation: "account.logout",
    operands: ["currentUser"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/csrf",
    auth: ["access"],
    operation: "csrf.issue",
    operands: ["currentUser"],
    adminOnly: false,
    csrf: "csrf-issue",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/operations/:id",
    auth: ["access", "app_password", "share"],
    operation: "operation.read",
    operands: ["operation", "originalOperands"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/search",
    auth: ["access"],
    operation: "search.read",
    operands: ["scopeRoot", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/recent",
    auth: ["access"],
    operation: "recent.read",
    operands: ["scopeRoot", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/starred",
    auth: ["access"],
    operation: "starred.read",
    operands: ["scopeRoot", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/shared-with-me",
    auth: ["access"],
    operation: "shared.read",
    operands: ["currentUser", "mounts", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/stats",
    auth: ["access"],
    operation: "account.read",
    operands: ["currentUser", "space", "scopeRoot"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/nodes/:nodeId",
    auth: ["access"],
    operation: "node.read",
    operands: ["node", "ancestors"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/nodes/:nodeId/path",
    auth: ["access"],
    operation: "node.read",
    operands: ["node", "ancestors"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/nodes/:nodeId/children",
    auth: ["access"],
    operation: "node.read",
    operands: ["node", "children", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/nodes/:nodeId/content",
    auth: ["access"],
    operation: "node.read",
    operands: ["node", "ancestors", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/nodes/:nodeId/content",
    auth: ["access"],
    operation: "node.read",
    operands: ["node", "ancestors", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/nodes/:nodeId/thumb",
    auth: ["access"],
    operation: "node.read",
    operands: ["node", "ancestors", "blob", "variant"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/nodes/:nodeId/thumb",
    auth: ["access"],
    operation: "node.read",
    operands: ["node", "ancestors", "blob", "variant"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/nodes/:nodeId/preview",
    auth: ["access"],
    operation: "node.read",
    operands: ["node", "ancestors", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/nodes/:nodeId/preview",
    auth: ["access"],
    operation: "node.read",
    operands: ["node", "ancestors", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/nodes",
    auth: ["access"],
    operation: "node.create",
    operands: ["parent", "space"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PATCH",
    template: "/api/v1/nodes/:nodeId",
    auth: ["access"],
    operation: "node.rename",
    operands: ["node", "parent"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PUT",
    template: "/api/v1/nodes/:nodeId/content",
    auth: ["access"],
    operation: "node.content.write",
    operands: ["node", "parent", "oldBlob", "newBlob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/nodes/:nodeId",
    auth: ["access"],
    operation: "node.trash",
    operands: ["node", "parent", "descendants"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/nodes/:nodeId/move",
    auth: ["access"],
    operation: "node.move",
    operands: [
      "source",
      "sourceParent",
      "destinationParent",
      "overwriteTarget",
      "sourceAncestors",
      "destinationAncestors",
    ],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/nodes/:nodeId/copy",
    auth: ["access"],
    operation: "node.copy",
    operands: [
      "source",
      "destinationParent",
      "overwriteTarget",
      "sourceAncestors",
      "destinationAncestors",
    ],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PUT",
    template: "/api/v1/nodes/:nodeId/star",
    auth: ["access"],
    operation: "node.star",
    operands: ["currentUser", "node"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/nodes/:nodeId/zip",
    auth: ["access"],
    operation: "zip.create",
    operands: ["root", "subtree", "blobs", "budgetId"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/zips/:id",
    auth: ["access"],
    operation: "zip.read",
    operands: ["manifest", "nodes", "blobs", "budgetId", "ticket"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/nodes/:nodeId/gallery",
    auth: ["access"],
    operation: "gallery.read",
    operands: ["folder", "candidates", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/nodes/:nodeId/tracks",
    auth: ["access"],
    operation: "audio.read",
    operands: ["folder", "tracks", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PATCH",
    template: "/api/v1/nodes/:nodeId/audio",
    auth: ["access"],
    operation: "audio.metadata.write",
    operands: ["node", "blob", "audioMetadata"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PUT",
    template: "/api/v1/nodes/:nodeId/playback-state",
    auth: ["access"],
    operation: "playback_state.write",
    operands: ["currentUser", "node", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/library/items",
    auth: ["access"],
    operation: "library.read",
    operands: ["scopeRoot", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/library/items/:itemId",
    auth: ["access"],
    operation: "library.read",
    operands: ["item", "node", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PATCH",
    template: "/api/v1/library/items/:itemId",
    auth: ["access"],
    operation: "library.write",
    operands: ["item", "node", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/library/:nodeId",
    auth: ["access"],
    operation: "library.read",
    operands: ["node", "blob", "index"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/library/:nodeId/pages/:page",
    auth: ["access"],
    operation: "library.read",
    operands: ["node", "blob", "index", "page"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/library/:nodeId/pages/:page",
    auth: ["access"],
    operation: "library.read",
    operands: ["node", "blob", "index", "page"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/library/:nodeId/pages/:page/thumb",
    auth: ["access"],
    operation: "library.read",
    operands: ["node", "blob", "index", "page"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/library/:nodeId/pages/:page/thumb",
    auth: ["access"],
    operation: "library.read",
    operands: ["node", "blob", "index", "page"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/library/:nodeId/entries/:entryToken",
    auth: ["access"],
    operation: "library.read",
    operands: ["node", "blob", "index", "entry"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/library/:nodeId/entries/:entryToken",
    auth: ["access"],
    operation: "library.read",
    operands: ["node", "blob", "index", "entry"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PUT",
    template: "/api/v1/library/:nodeId/reading-state",
    auth: ["access"],
    operation: "reading_state.write",
    operands: ["currentUser", "node", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/library/roots",
    auth: ["access"],
    operation: "library.read",
    operands: ["currentUser"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/library/roots",
    auth: ["access"],
    operation: "library.write",
    operands: ["currentUser", "rootNode"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/library/roots/:nodeId",
    auth: ["access"],
    operation: "library.write",
    operands: ["currentUser", "rootNode"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/uploads",
    auth: ["access"],
    operation: "upload.create",
    operands: ["parent", "target", "space", "declaredSize", "mode"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/uploads/:uploadId",
    auth: ["access"],
    operation: "upload.read",
    operands: ["upload", "parent", "target"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PUT",
    template: "/api/v1/uploads/:uploadId/content",
    auth: ["access"],
    operation: "upload.write",
    operands: ["upload", "parent", "target", "knownLength"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PUT",
    template: "/api/v1/uploads/:uploadId/parts/:partNumber",
    auth: ["access"],
    operation: "upload.write",
    operands: ["upload", "parent", "target", "part"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/uploads/:uploadId/complete",
    auth: ["access"],
    operation: "upload.complete",
    operands: ["upload", "parent", "target", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/uploads/:uploadId",
    auth: ["access"],
    operation: "upload.abort",
    operands: ["upload", "parent", "target"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/trash",
    auth: ["access"],
    operation: "trash.read",
    operands: ["space", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/trash/:opId/restore",
    auth: ["access"],
    operation: "node.restore",
    operands: ["trashOp", "root", "destinationParent"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/trash/:opId/purge",
    auth: ["access"],
    operation: "node.purge",
    operands: ["trashOp", "root", "members"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/shares",
    auth: ["access"],
    operation: "share.read",
    operands: ["currentUser"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/shares",
    auth: ["access"],
    operation: "share.manage",
    operands: ["currentUser", "root"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/shares/:shareId",
    auth: ["access"],
    operation: "share.read",
    operands: ["share", "root"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PATCH",
    template: "/api/v1/shares/:shareId",
    auth: ["access"],
    operation: "share.manage",
    operands: ["share", "root"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/shares/:shareId",
    auth: ["access"],
    operation: "share.disable",
    operands: ["share", "root", "owner"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/tags",
    auth: ["access"],
    operation: "tag.read",
    operands: ["currentUser", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/tags",
    auth: ["access"],
    operation: "tag.create",
    operands: ["currentUser", "tag"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "PATCH",
    template: "/api/v1/tags/:tagId",
    auth: ["access"],
    operation: "tag.update",
    operands: ["currentUser", "tag"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/tags/:tagId",
    auth: ["access"],
    operation: "tag.delete",
    operands: ["currentUser", "tag", "nodes"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/content-session",
    auth: ["access"],
    operation: "content.session.create",
    operands: ["targetSetId", "targetSetHash", "nodes", "blobs", "budgetId"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/tickets/:ticketId",
    auth: ["access"],
    operation: "ticket.cancel",
    operands: ["ticket", "session", "budgetId"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/app-passwords",
    auth: ["access"],
    operation: "credential.read",
    operands: ["currentUser"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/app-passwords",
    auth: ["access"],
    operation: "credential.create",
    operands: ["currentUser"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/app-passwords/:credentialId",
    auth: ["access"],
    operation: "credential.revoke",
    operands: ["currentUser", "credential"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/jobs/:jobId",
    auth: ["access"],
    operation: "job.read",
    operands: ["job", "originalOperands"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/jobs/:jobId/cancel",
    auth: ["access"],
    operation: "job.cancel",
    operands: ["job", "originalOperands"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/jobs/:jobId/retry",
    auth: ["access"],
    operation: "job.retry",
    operands: ["job", "originalOperands"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/admin/dlq",
    auth: ["access"],
    operation: "admin.dlq",
    operands: ["dlqCursor"],
    adminOnly: true,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/admin/dlq/:jobId/requeue",
    auth: ["access"],
    operation: "admin.dlq",
    operands: ["job", "originalOperands"],
    adminOnly: true,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/admin/users/:userId/disable",
    auth: ["access"],
    operation: "admin.user.disable",
    operands: ["actor", "targetUser"],
    adminOnly: true,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/admin/transfer",
    auth: ["access"],
    operation: "admin.transfer",
    operands: ["actor", "targetUser", "newAdmin"],
    adminOnly: true,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/admin/locks/:lockId/force-unlock",
    auth: ["access"],
    operation: "admin.lock.force_unlock",
    operands: ["actor", "lock", "node"],
    adminOnly: true,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/automation/nodes",
    auth: ["service"],
    operation: "automation.list",
    operands: ["service", "mappedUser", "space", "scopeRoot", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/automation/nodes/:nodeId",
    auth: ["service"],
    operation: "automation.metadata.read",
    operands: ["service", "mappedUser", "space", "node", "ancestors"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId",
    auth: ["share"],
    operation: "share.read",
    operands: ["share", "root"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/children/:nodeId",
    auth: ["share"],
    operation: "share.read",
    operands: ["share", "node", "ancestors", "children"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/content/:nodeId",
    auth: ["share"],
    operation: "share.read",
    operands: ["share", "node", "ancestors", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/public/shares/:shareId/content/:nodeId",
    auth: ["share"],
    operation: "share.read",
    operands: ["share", "node", "ancestors", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/thumb/:nodeId",
    auth: ["share"],
    operation: "share.read",
    operands: ["share", "node", "ancestors", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/public/shares/:shareId/thumb/:nodeId",
    auth: ["share"],
    operation: "share.read",
    operands: ["share", "node", "ancestors", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/public/shares/:shareId/unlock",
    auth: ["public"],
    operation: "share.unlock",
    operands: ["share"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/public/shares/:shareId/logout",
    auth: ["share"],
    operation: "share.logout",
    operands: ["share", "session"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/public/shares/:shareId/tickets",
    auth: ["share"],
    operation: "share.read",
    operands: ["share", "session", "targetSetId", "targetSetHash", "budgetId"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/public/shares/:shareId/tickets/:ticketId",
    auth: ["share"],
    operation: "ticket.cancel",
    operands: ["share", "ticket", "session", "budgetId"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/public/shares/:shareId/content-session",
    auth: ["share"],
    operation: "content.session.create",
    operands: ["share", "session", "targetSetId", "targetSetHash", "budgetId"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/public/shares/:shareId/nodes/:nodeId/zip",
    auth: ["share"],
    operation: "zip.create",
    operands: ["share", "root", "subtree", "blobs", "budgetId"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/zips/:zipId",
    auth: ["share"],
    operation: "zip.read",
    operands: ["share", "manifest", "nodes", "blobs", "budgetId", "ticket"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/gallery",
    auth: ["share"],
    operation: "gallery.read",
    operands: ["share", "root", "candidates", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/tracks",
    auth: ["share"],
    operation: "audio.read",
    operands: ["share", "root", "tracks", "cursor"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/library/:nodeId",
    auth: ["share"],
    operation: "library.read",
    operands: ["share", "node", "blob", "index"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/library/:nodeId/pages/:page",
    auth: ["share"],
    operation: "library.read",
    operands: ["share", "node", "blob", "index", "page"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/public/shares/:shareId/library/:nodeId/pages/:page",
    auth: ["share"],
    operation: "library.read",
    operands: ["share", "node", "blob", "index", "page"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/library/:nodeId/entries/:entryToken",
    auth: ["share"],
    operation: "library.read",
    operands: ["share", "node", "blob", "index", "entry"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/api/v1/public/shares/:shareId/library/:nodeId/entries/:entryToken",
    auth: ["share"],
    operation: "library.read",
    operands: ["share", "node", "blob", "index", "entry"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/public/shares/:shareId/nodes",
    auth: ["share"],
    operation: "node.create",
    operands: ["share", "parent"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "PATCH",
    template: "/api/v1/public/shares/:shareId/nodes/:nodeId",
    auth: ["share"],
    operation: "node.rename",
    operands: ["share", "node", "parent", "ancestors"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/public/shares/:shareId/nodes/:nodeId",
    auth: ["share"],
    operation: "node.trash",
    operands: ["share", "node", "parent", "ancestors"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/public/shares/:shareId/uploads",
    auth: ["share"],
    operation: "upload.create",
    operands: ["share", "parent", "target", "declaredSize", "mode"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "GET",
    template: "/api/v1/public/shares/:shareId/uploads/:uploadId",
    auth: ["share"],
    operation: "upload.read",
    operands: ["share", "upload", "parent", "target"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "PUT",
    template: "/api/v1/public/shares/:shareId/uploads/:uploadId/content",
    auth: ["share"],
    operation: "upload.write",
    operands: ["share", "upload", "knownLength"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "PUT",
    template: "/api/v1/public/shares/:shareId/uploads/:uploadId/parts/:partNumber",
    auth: ["share"],
    operation: "upload.write",
    operands: ["share", "upload", "part"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/public/shares/:shareId/uploads/:uploadId/complete",
    auth: ["share"],
    operation: "upload.complete",
    operands: ["share", "upload", "parent", "target", "blob"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/api/v1/public/shares/:shareId/uploads/:uploadId",
    auth: ["share"],
    operation: "upload.abort",
    operands: ["share", "upload"],
    adminOnly: false,
    csrf: "public-form",
  },
  {
    host: "app",
    method: "OPTIONS",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.options",
    operands: ["credential", "source"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "OPTIONS",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.options",
    operands: ["credential", "source"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "PROPFIND",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.propfind",
    operands: ["source", "ancestors", "properties", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "PROPFIND",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.propfind",
    operands: ["source", "ancestors", "properties", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "PROPPATCH",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.proppatch",
    operands: ["source", "ancestors", "properties", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "PROPPATCH",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.proppatch",
    operands: ["source", "ancestors", "properties", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "MKCOL",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.mkcol",
    operands: ["sourceParent", "ancestors", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "MKCOL",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.mkcol",
    operands: ["sourceParent", "ancestors", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "GET",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.read",
    operands: ["source", "ancestors", "blob"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "GET",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.read",
    operands: ["source", "ancestors", "blob"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.read",
    operands: ["source", "ancestors", "blob"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "HEAD",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.read",
    operands: ["source", "ancestors", "blob"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "PUT",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.put",
    operands: ["source", "sourceParent", "oldBlob", "newBlob", "ancestors", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "PUT",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.put",
    operands: ["source", "sourceParent", "oldBlob", "newBlob", "ancestors", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.delete",
    operands: ["source", "sourceParent", "descendants", "ancestors", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "DELETE",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.delete",
    operands: ["source", "sourceParent", "descendants", "ancestors", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "COPY",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.copy",
    operands: [
      "source",
      "destinationParent",
      "overwriteTarget",
      "sourceAncestors",
      "destinationAncestors",
      "locks",
    ],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "COPY",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.copy",
    operands: [
      "source",
      "destinationParent",
      "overwriteTarget",
      "sourceAncestors",
      "destinationAncestors",
      "locks",
    ],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "MOVE",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.move",
    operands: [
      "source",
      "sourceParent",
      "destinationParent",
      "overwriteTarget",
      "sourceAncestors",
      "destinationAncestors",
      "locks",
    ],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "MOVE",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.move",
    operands: [
      "source",
      "sourceParent",
      "destinationParent",
      "overwriteTarget",
      "sourceAncestors",
      "destinationAncestors",
      "locks",
    ],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "LOCK",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.lock",
    operands: ["source?", "sourceParent", "nodeCreate?", "ancestors", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "LOCK",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.lock",
    operands: ["source?", "sourceParent", "nodeCreate?", "ancestors", "locks"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "UNLOCK",
    template: "/dav",
    auth: ["app_password"],
    operation: "dav.unlock",
    operands: ["source", "ancestors", "lock"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "app",
    method: "UNLOCK",
    template: "/dav/*path",
    auth: ["app_password"],
    operation: "dav.unlock",
    operands: ["source", "ancestors", "lock"],
    adminOnly: false,
    csrf: "dav",
  },
  {
    host: "content",
    method: "OPTIONS",
    template: "/session",
    auth: ["public"],
    operation: "content.session.accept",
    operands: ["requestOrigin"],
    adminOnly: false,
    csrf: "cross-origin-content",
  },
  {
    host: "content",
    method: "POST",
    template: "/session",
    auth: ["public"],
    operation: "content.session.accept",
    operands: ["signedTicket", "targetSetId", "targetSetHash", "budgetId"],
    adminOnly: false,
    csrf: "cross-origin-content",
  },
  {
    host: "content",
    method: "GET",
    template: "/c/:nodeId/:blobId",
    auth: ["content_cookie"],
    operation: "content.read",
    operands: ["session", "node", "blob", "budgetId"],
    adminOnly: false,
    csrf: "cross-origin-content",
  },
  {
    host: "content",
    method: "HEAD",
    template: "/c/:nodeId/:blobId",
    auth: ["content_cookie"],
    operation: "content.read",
    operands: ["session", "node", "blob"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "content",
    method: "GET",
    template: "/c/:nodeId/:blobId/pages/:page",
    auth: ["content_cookie"],
    operation: "content.read",
    operands: ["session", "node", "blob", "index", "page"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "content",
    method: "HEAD",
    template: "/c/:nodeId/:blobId/pages/:page",
    auth: ["content_cookie"],
    operation: "content.read",
    operands: ["session", "node", "blob", "index", "page"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "content",
    method: "GET",
    template: "/c/:nodeId/:blobId/entries/:entryToken",
    auth: ["content_cookie"],
    operation: "content.read",
    operands: ["session", "node", "blob", "index", "entry"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "content",
    method: "HEAD",
    template: "/c/:nodeId/:blobId/entries/:entryToken",
    auth: ["content_cookie"],
    operation: "content.read",
    operands: ["session", "node", "blob", "index", "entry"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "content",
    method: "GET",
    template: "/reader/index.html",
    auth: ["public"],
    operation: "reader.shell",
    operands: ["readerAssetManifest"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "content",
    method: "GET",
    template: "/reader/:asset",
    auth: ["public"],
    operation: "reader.shell",
    operands: ["readerAssetManifest"],
    adminOnly: false,
    csrf: "same-origin-json",
  },
  {
    host: "app",
    method: "POST",
    template: "/api/v1/public/shares/:shareId/csrf",
    auth: ["share"],
    operation: "csrf.issue",
    operands: ["share", "session"],
    adminOnly: false,
    csrf: "public-csrf-issue",
  },
] as const satisfies readonly RouteContract[];
