export const exportTables = [
  "users",
  "control",
  "settings",
  "sessions",
  "app_passwords",
  "spaces",
  "blobs",
  "trash_ops",
  "nodes",
  "permits",
  "operations",
  "operation_steps",
  "audit",
  "outbox",
  "trash_members",
  "node_props",
  "tags",
  "node_tags",
  "node_media",
  "node_audio",
  "library_items",
  "archive_index",
  "user_reading_state",
  "user_playback_state",
  "shares",
  "share_grants",
  "share_sessions",
  "content_target_sets",
  "content_sessions",
  "node_versions",
  "blob_pins",
  "gc_candidates",
  "locks",
  "uploads",
  "upload_parts",
  "job_leases",
  "derivative_results",
  "backup_runs",
  "search_index",
] as const;

export function buildExportArguments(databaseName: string): string[] {
  return exportTables.flatMap((table) => ["--database", databaseName, `--table=${table}`]);
}
